services:
  - type: web
    name: wanderlust-docker
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    plan: free
    region: oregon
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://YOUR_USER:YOUR_PASS@cluster0.mongodb.net/wanderlust
